# Welcome to Serverless!
# For full config options, check the docs:
#    docs.serverless.com

service: platypus-lambda-cmc

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  individually: true
  # patterns:
  #   - "!exclude-me.js"
  #   - "!exclude-me-dir/**"
  #   - include-me.js
  #   - include-me-dir/**

plugins:
  - serverless-offline
  - serverless-api-gateway-caching

functions:
  current_time:
    runtime: nodejs14.x
    handler: current_time/handler.currentTime
    events:
      - http:
          path: /current_time
          method: get
          cors: true
  circulating_supply:
    runtime: nodejs14.x
    handler: circulating_supply/handler.circulatingSupply
    events:
      - http:
          path: /circulating_supply
          method: get
          cors: true
  cmc_price:
    runtime: nodejs14.x
    handler: cmc_price/handler.cmcPrice
    events:
      - http:
          path: /cmc_price
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 600 # cache cmc price for 10mins
            dataEncrypted: true # default is false
            cacheKeyParameters:
              - name: request.querystring.id
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
